/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as ElectionsIdRouteImport } from './routes/elections.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardNominateRouteImport } from './routes/_authenticated/dashboard.nominate'
import { Route as AuthenticatedDashboardHistoryRouteImport } from './routes/_authenticated/dashboard.history'
import { Route as AuthenticatedDashboardElectionsRouteImport } from './routes/_authenticated/dashboard.elections'
import { Route as AuthenticatedAdminVotersRouteImport } from './routes/_authenticated/admin.voters'
import { Route as AuthenticatedAdminElectionsRouteImport } from './routes/_authenticated/admin.elections'
import { Route as AuthenticatedAdminCandidatesRouteImport } from './routes/_authenticated/admin.candidates'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedDashboardVoteElectionIdRouteImport } from './routes/_authenticated/dashboard.vote.$electionId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResultsRoute,
} as any)
const ElectionsIdRoute = ElectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ElectionsRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNominateRoute =
  AuthenticatedDashboardNominateRouteImport.update({
    id: '/nominate',
    path: '/nominate',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHistoryRoute =
  AuthenticatedDashboardHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardElectionsRoute =
  AuthenticatedDashboardElectionsRouteImport.update({
    id: '/elections',
    path: '/elections',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminVotersRoute =
  AuthenticatedAdminVotersRouteImport.update({
    id: '/voters',
    path: '/voters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminElectionsRoute =
  AuthenticatedAdminElectionsRouteImport.update({
    id: '/elections',
    path: '/elections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCandidatesRoute =
  AuthenticatedAdminCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardVoteElectionIdRoute =
  AuthenticatedDashboardVoteElectionIdRouteImport.update({
    id: '/vote/$electionId',
    path: '/vote/$electionId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/elections': typeof ElectionsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/results': typeof ResultsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/elections/$id': typeof ElectionsIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/candidates': typeof AuthenticatedAdminCandidatesRoute
  '/admin/elections': typeof AuthenticatedAdminElectionsRoute
  '/admin/voters': typeof AuthenticatedAdminVotersRoute
  '/dashboard/elections': typeof AuthenticatedDashboardElectionsRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/nominate': typeof AuthenticatedDashboardNominateRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/vote/$electionId': typeof AuthenticatedDashboardVoteElectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/elections': typeof ElectionsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/results': typeof ResultsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/elections/$id': typeof ElectionsIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/candidates': typeof AuthenticatedAdminCandidatesRoute
  '/admin/elections': typeof AuthenticatedAdminElectionsRoute
  '/admin/voters': typeof AuthenticatedAdminVotersRoute
  '/dashboard/elections': typeof AuthenticatedDashboardElectionsRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/nominate': typeof AuthenticatedDashboardNominateRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/vote/$electionId': typeof AuthenticatedDashboardVoteElectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/elections': typeof ElectionsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/results': typeof ResultsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/elections/$id': typeof ElectionsIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/candidates': typeof AuthenticatedAdminCandidatesRoute
  '/_authenticated/admin/elections': typeof AuthenticatedAdminElectionsRoute
  '/_authenticated/admin/voters': typeof AuthenticatedAdminVotersRoute
  '/_authenticated/dashboard/elections': typeof AuthenticatedDashboardElectionsRoute
  '/_authenticated/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/_authenticated/dashboard/nominate': typeof AuthenticatedDashboardNominateRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/vote/$electionId': typeof AuthenticatedDashboardVoteElectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/elections'
    | '/faqs'
    | '/results'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/elections/$id'
    | '/results/$id'
    | '/admin/audit'
    | '/admin/candidates'
    | '/admin/elections'
    | '/admin/voters'
    | '/dashboard/elections'
    | '/dashboard/history'
    | '/dashboard/nominate'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/vote/$electionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/elections'
    | '/faqs'
    | '/results'
    | '/sitemap.xml'
    | '/elections/$id'
    | '/results/$id'
    | '/admin/audit'
    | '/admin/candidates'
    | '/admin/elections'
    | '/admin/voters'
    | '/dashboard/elections'
    | '/dashboard/history'
    | '/dashboard/nominate'
    | '/dashboard/profile'
    | '/admin'
    | '/dashboard'
    | '/dashboard/vote/$electionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/elections'
    | '/faqs'
    | '/results'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/elections/$id'
    | '/results/$id'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/candidates'
    | '/_authenticated/admin/elections'
    | '/_authenticated/admin/voters'
    | '/_authenticated/dashboard/elections'
    | '/_authenticated/dashboard/history'
    | '/_authenticated/dashboard/nominate'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/vote/$electionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ElectionsRoute: typeof ElectionsRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  ResultsRoute: typeof ResultsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof ResultsRoute
    }
    '/elections/$id': {
      id: '/elections/$id'
      path: '/$id'
      fullPath: '/elections/$id'
      preLoaderRoute: typeof ElectionsIdRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/nominate': {
      id: '/_authenticated/dashboard/nominate'
      path: '/nominate'
      fullPath: '/dashboard/nominate'
      preLoaderRoute: typeof AuthenticatedDashboardNominateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/history': {
      id: '/_authenticated/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AuthenticatedDashboardHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/elections': {
      id: '/_authenticated/dashboard/elections'
      path: '/elections'
      fullPath: '/dashboard/elections'
      preLoaderRoute: typeof AuthenticatedDashboardElectionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/voters': {
      id: '/_authenticated/admin/voters'
      path: '/voters'
      fullPath: '/admin/voters'
      preLoaderRoute: typeof AuthenticatedAdminVotersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/elections': {
      id: '/_authenticated/admin/elections'
      path: '/elections'
      fullPath: '/admin/elections'
      preLoaderRoute: typeof AuthenticatedAdminElectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/candidates': {
      id: '/_authenticated/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AuthenticatedAdminCandidatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/vote/$electionId': {
      id: '/_authenticated/dashboard/vote/$electionId'
      path: '/vote/$electionId'
      fullPath: '/dashboard/vote/$electionId'
      preLoaderRoute: typeof AuthenticatedDashboardVoteElectionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCandidatesRoute: typeof AuthenticatedAdminCandidatesRoute
  AuthenticatedAdminElectionsRoute: typeof AuthenticatedAdminElectionsRoute
  AuthenticatedAdminVotersRoute: typeof AuthenticatedAdminVotersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCandidatesRoute: AuthenticatedAdminCandidatesRoute,
  AuthenticatedAdminElectionsRoute: AuthenticatedAdminElectionsRoute,
  AuthenticatedAdminVotersRoute: AuthenticatedAdminVotersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardElectionsRoute: typeof AuthenticatedDashboardElectionsRoute
  AuthenticatedDashboardHistoryRoute: typeof AuthenticatedDashboardHistoryRoute
  AuthenticatedDashboardNominateRoute: typeof AuthenticatedDashboardNominateRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardVoteElectionIdRoute: typeof AuthenticatedDashboardVoteElectionIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardElectionsRoute: AuthenticatedDashboardElectionsRoute,
    AuthenticatedDashboardHistoryRoute: AuthenticatedDashboardHistoryRoute,
    AuthenticatedDashboardNominateRoute: AuthenticatedDashboardNominateRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardVoteElectionIdRoute:
      AuthenticatedDashboardVoteElectionIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ElectionsRouteChildren {
  ElectionsIdRoute: typeof ElectionsIdRoute
}

const ElectionsRouteChildren: ElectionsRouteChildren = {
  ElectionsIdRoute: ElectionsIdRoute,
}

const ElectionsRouteWithChildren = ElectionsRoute._addFileChildren(
  ElectionsRouteChildren,
)

interface ResultsRouteChildren {
  ResultsIdRoute: typeof ResultsIdRoute
}

const ResultsRouteChildren: ResultsRouteChildren = {
  ResultsIdRoute: ResultsIdRoute,
}

const ResultsRouteWithChildren =
  ResultsRoute._addFileChildren(ResultsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ElectionsRoute: ElectionsRouteWithChildren,
  FaqsRoute: FaqsRoute,
  ResultsRoute: ResultsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
