// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function normalizeEnvValue(value?: string) {
  if (!value) return undefined;
  return value.replace(/^['"]|['"]$/g, '');
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = normalizeEnvValue(import.meta.env.VITE_SUPABASE_URL) || normalizeEnvValue(process.env.SUPABASE_URL);
  const SUPABASE_PUBLISHABLE_KEY =
    normalizeEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    normalizeEnvValue(import.meta.env.VITE_SUPABASE_KEY) ||
    normalizeEnvValue(process.env.SUPABASE_PUBLISHABLE_KEY) ||
    normalizeEnvValue(process.env.SUPABASE_KEY);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Debug: show which URL/key is being used in the browser console (masked key)
  if (typeof window !== 'undefined') {
    try {
      const maskedKey = SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.slice(0, 6)}…` : 'MISSING';
      // eslint-disable-next-line no-console
      console.debug(`[Supabase] URL=${SUPABASE_URL} PUBLISHABLE_KEY=${maskedKey}`);
    } catch {}
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

